-- ============================================================
-- SCHEMA: Streams Tick Level - Para NUEVA Base de Datos
-- Uso: Crear desde cero en una DB limpia
-- ============================================================

-- 1. Extensión TimescaleDB
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ============================================================
-- 2. TABLA: trades (trades crudos)
-- ============================================================
DROP TABLE IF EXISTS trades CASCADE;

CREATE TABLE trades (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ts          TIMESTAMPTZ NOT NULL,
    symbol      TEXT        NOT NULL,
    exchange    TEXT        NOT NULL,
    price       DOUBLE PRECISION NOT NULL,
    qty         DOUBLE PRECISION NOT NULL,
    trade_id    TEXT,
    side        TEXT
);

-- Convertir a hypertable (TimescaleDB)
SELECT create_hypertable('trades', 'ts',
    chunk_time_interval => INTERVAL '1 hour'
);

-- Índices
CREATE INDEX idx_trades_symbol ON trades (symbol);
CREATE INDEX idx_trades_ts ON trades (ts DESC);
CREATE INDEX idx_trades_exchange ON trades (exchange);

-- Compresión
ALTER TABLE trades SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'symbol,exchange'
);
SELECT add_compression_policy('trades', INTERVAL '1 hour');

-- ============================================================
-- 3. TABLA: anomalies (resultados Z-score)
-- ============================================================
DROP TABLE IF EXISTS anomalies CASCADE;

CREATE TABLE anomalies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ts              TIMESTAMPTZ NOT NULL,
    symbol          TEXT        NOT NULL,
    window_start    TIMESTAMPTZ NOT NULL,
    window_end      TIMESTAMPTZ NOT NULL,
    mean_price      DOUBLE PRECISION,
    std_price       DOUBLE PRECISION,
    last_price      DOUBLE PRECISION NOT NULL,
    z_score         DOUBLE PRECISION NOT NULL,
    is_anomaly      BOOLEAN          NOT NULL,
    anomaly_type    TEXT,
    trade_count     BIGINT
);

-- Hypertable
SELECT create_hypertable('anomalies', 'ts',
    chunk_time_interval => INTERVAL '1 hour'
);

-- Índices
CREATE INDEX idx_anomalies_symbol ON anomalies (symbol);
CREATE INDEX idx_anomalies_ts ON anomalies (ts DESC);
CREATE INDEX idx_anomalies_is_anomaly ON anomalies (is_anomaly);

-- Compresión
ALTER TABLE anomalies SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'symbol,anomaly_type'
);
SELECT add_compression_policy('anomalies', INTERVAL '1 hour');

-- ============================================================
-- 4. TABLA: aggregated_metrics
-- ============================================================
DROP TABLE IF EXISTS aggregated_metrics CASCADE;

CREATE TABLE aggregated_metrics (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ts              TIMESTAMPTZ NOT NULL,
    symbol          TEXT        NOT NULL,
    avg_price       DOUBLE PRECISION,
    min_price       DOUBLE PRECISION,
    max_price       DOUBLE PRECISION,
    total_volume    DOUBLE PRECISION,
    trade_count     BIGINT,
    window_minutes  INTEGER DEFAULT 1
);

SELECT create_hypertable('aggregated_metrics', 'ts',
    chunk_time_interval => INTERVAL '1 hour'
);

CREATE INDEX idx_aggregated_symbol ON aggregated_metrics (symbol);

-- ============================================================
-- 5. VISTA: v_recent_anomalies
-- ============================================================
CREATE OR REPLACE VIEW v_recent_anomalies AS
SELECT 
    symbol,
    COUNT(*) FILTER (WHERE is_anomaly) AS anomaly_count,
    MAX(z_score) AS max_z_score,
    COUNT(*) AS total_windows,
    MAX(ts) AS last_update
FROM anomalies
WHERE ts > NOW() - INTERVAL '1 hour'
GROUP BY symbol
ORDER BY anomaly_count DESC;

-- ============================================================
-- 6. CONTINUOUS AGGREGATE: cagg_anomalies_hourly
-- ============================================================
DROP MATERIALIZED VIEW IF EXISTS cagg_anomalies_hourly CASCADE;

CREATE MATERIALIZED VIEW cagg_anomalies_hourly
WITH (timescaledb.continuous)
AS
SELECT 
    symbol,
    time_bucket('5 minutes', ts) AS bucket,
    COUNT(*) FILTER (WHERE is_anomaly) AS anomaly_count,
    MAX(z_score) AS max_z_score,
    COUNT(*) AS total_windows,
    COUNT(*) FILTER (WHERE anomaly_type = 'SPIKE') AS spike_count,
    COUNT(*) FILTER (WHERE anomaly_type = 'DROP') AS drop_count,
    COUNT(*) FILTER (WHERE anomaly_type = 'VOLUME_SURGE') AS volume_surge_count
FROM anomalies
GROUP BY symbol, bucket
WITH NO DATA;

SELECT add_continuous_aggregate_policy('cagg_anomalies_hourly',
    start_offset => INTERVAL '1 hour',
    end_offset => INTERVAL '10 minutes',
    schedule_interval => INTERVAL '5 minutes'
);

CREATE INDEX IF NOT EXISTS idx_cagg_anomalies_symbol ON cagg_anomalies_hourly (symbol);
CREATE INDEX IF NOT EXISTS idx_cagg_anomalies_bucket ON cagg_anomalies_hourly (bucket DESC);
